name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 18.x, 16.x]

    steps:
      - name: Checkout of code from repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: list files in modules directory
        run: ls -la modules
      
      - name: npm install
        run: npm ci
        
      - name: tests
        run: npm test